name = "SDPNAL"
uuid = "f7a9608b-7678-5329-8a05-97541ebc462c"
repo = "https://github.com/jump-dev/SDPNAL.jl.git"
version = "0.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MATLAB = "10e44e05-a98a-55b3-a45b-ba969058deb6"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MATLAB = "0.7, 0.8"
MathOptInterface = "~0.9.21"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
